# Generated by Django 5.2.17 on 2026-10-10 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('pais', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True, default='Sin descripción', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('hotel', models.BooleanField(default=True)),
                ('valor', models.PositiveBigIntegerField()),
                ('disponible', models.BooleanField(default=True)),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Paquetes', to='viajes.destino')),
            ],
        ),
    ]
