# Generated by Django 6.1.2 on 2026-10-08 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destino',
            name='Pais',
        ),
    ]
