# Generated by Django 5.2.17 on 2026-10-10 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destino',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
